
# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
homeassistant:
  customize: !include customize.yaml

# 主题
frontend: !include themes.yaml
template: !include sidebar.yaml

# 实体创建
sensor:
  # 模板
  - platform: template
    sensors:
      number_lights_on:
        friendly_name: 开灯数量
        value_template: "{{ states.light | selectattr('state', 'eq', 'on') | selectattr('attributes.friendly_name', 'search', '灯') | list | count +
                            states.switch | selectattr('state', 'eq', 'on') | selectattr('attributes.friendly_name', 'search', '灯') | list | count +
                            states.input_boolean | selectattr('state', 'eq', 'on') | selectattr('attributes.friendly_name', 'search', '灯') | list | count }}"
      number_climates_on:
        friendly_name: 空调数量
        value_template: "{{ states.climate | rejectattr('state', 'eq', 'off') | list | count }}"
  # 日期时间
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time'
      - 'date_time_utc'
      - 'date_time_iso'
      - 'time_date'
      - 'time_utc'
      - 'beat'
